org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

maven_group=cn.fandmc
mod_version=0.1.0-SNAPSHOT
loom_version=1.17.19
loader_version=0.19.3

minecraft_version_1201=1.20.1
fabric_api_version_1201=0.92.11+1.20.1

minecraft_version_1214=1.21.4
fabric_api_version_1214=0.119.4+1.21.4

minecraft_version_262=26.2
fabric_api_version_262=0.158.0+26.2

skija_version=0.143.17
skija_types_version=0.2.0
skija_annotations_version=20.1.0
lwjgl_compile_version=3.3.1
lwjgl_nanovg_version_1201=3.3.2
lwjgl_nanovg_version_1214=3.3.3
lwjgl_nanovg_version_262=3.4.1
junit_version=5.14.1
jspecify_version=1.0.0
japicmp_version=0.26.1
api_baseline_version=0.1.0
